# Simple workflow for deploying static content to GitHub Pages
# 推送到preview 分支时候自动打包部署项目
name: 演示部署

on:
  # 仅在推送到默认分支时运行。
  push:
    branches: ['preview']

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: 打包
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: 安装node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
      - name: 安装pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8
      - name: 安装项目依赖
        run: pnpm install
      - name: 构建
        run: pnpm build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          # Upload dist repository
          path: './dist'
          name: github-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: artifact
